# Generated by Django 5.1.4 on 2025-01-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_supplements"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaloiresBurnt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("caloriesburnt", models.IntegerField()),
            ],
        ),
    ]
