# Generated by Django 5.1.4 on 2025-01-13 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_caloiresburnt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaloiresBurnt",
            new_name="CaloriesBurnt",
        ),
    ]
