# Generated by Django 5.1.4 on 2025-01-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_consume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='calorie_burnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.caloriesburnt'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.food'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='supplement_consumed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.supplements'),
        ),
    ]
